#!/usr/bin/env python3
"""
Generates an animated terminal style GitHub profile card, producing both
assets/dark.svg and assets/light.svg so the card looks right no matter which
GitHub theme the visitor is using.

Everything you would normally want to tweak lives in CONFIG, ASCII_ART and
INFO below. Stats such as repos, stars and followers are pulled live from
the GitHub API when this script runs inside GitHub Actions. If the API call
fails for any reason, the script quietly falls back to placeholder values
instead of crashing the whole workflow.
"""

import json
import os
import urllib.request
from datetime import datetime, timezone, timedelta
from html import escape
from pathlib import Path

# This section holds the basic settings for the card. USERNAME is used both
# for the terminal window title and for pulling live stats from the GitHub
# API, so make sure it matches your actual GitHub handle.
# CONFIG
USERNAME = "RanaZaid26194"

# This is the ascii portrait file produced by setup/photo_to_ascii.py. It is
# read once when the card is rendered and is never written to by this script.
PORTRAIT_FILE = "portrait.txt"   # generated by setup/photo_to_ascii.py

def load_portrait():
    # Reads the ascii art line by line so it can be drawn one row at a time
    # later on. If the file is missing (for example on a fresh fork before
    # anyone has generated their own portrait yet), we show a friendly
    # placeholder instead of letting the whole script fail.
    f = Path(__file__).parent / PORTRAIT_FILE
    if f.exists():
        return f.read_text(encoding="utf-8").rstrip("\n").split("\n")
    return ["[ portrait.txt missing ]"]


# This is the actual content shown in the info panel next to the ascii art.
# Each row is a tuple of label, value and a colour key that decides which
# CSS class the value gets painted with. A handful of special labels such as
# __header__, __section__ and __blank__ are treated as layout instructions
# rather than real rows, and are handled specially inside render() below.
# (label, value, colour key)  |  colour key options: key, val, accent, warn, muted
INFO = [
    ("__header__", "rana zaid", ""),
    ("__rule__", "", ""),
    ("Role",     "CS Undergraduate @ FAST-NUCES, Lahore", "val"),
    ("Edu",      "BS Computer Science  ·  Class of 2029", "val"),
    ("Focus",    "Automation  ·  Systems Integration  ·  Game Dev", "accent"),
    ("Sem",      "3rd semester  ·  CGPA 3.77  ·  2x Dean's List", "val"),
    ("Approach", "end-to-end builder — automation, full-stack apps,", "val"),
    ("",         "small tools that solve problems I actually run into", "muted"),
    ("Learning", "AI/ML fundamentals, applied where they meet", "val"),
    ("",         "the tools I already build", "muted"),
    ("__blank__", "", ""),
    ("__section__", "~/stack", ""),
    ("Lang",     "Python · C++ · C", "val"),
    # JS and SQL, add back in when ready:
    # ("Lang",     "Python · C++ · C · JavaScript · SQL", "val"),
    ("Backend",  "FastAPI · Playwright · REST API", "val"),
    # Node.js, add back in when ready:
    # ("Backend",  "FastAPI · Node.js · Playwright · REST API", "val"),
    ("Infra",    "Supabase · Netlify · Vercel · GitHub Actions · Git", "val"),
    ("__blank__", "", ""),
    ("__section__", "~/projects", ""),
    ("Vigil-X",  "Playwright automation for the NUCES FLEX portal", "warn"),
    ("",         "multi-account login, data collection, reCAPTCHA", "muted"),
    ("Skeptix",  "Citation-backed AI research assistant", "warn"),
    ("",         "Supabase + Google OAuth · Skeptic Mode fact-checking", "muted"),
    ("",         "built at MIT Hack Nation's 5th National Hackathon", "muted"),
    ("Haunt Spire", "C++ tower defense game built with SFML 3.0.2", "warn"),
    ("",         "custom audio, multi-map, isometric 2.5D, flight AI", "muted"),
    ("SnakeX",   "2D Snake game built with C++ and SFML", "warn"),
    ("",         "multiple levels, varied food types, save/load", "muted"),
    ("Gpify",    "Offline GPA calculator for FAST-NUCES students", "warn"),
    ("",         "grading schemes · what-if mode · PDF/PNG export", "muted"),
    ("__blank__", "", ""),
    # ("__section__", "~/highlights", ""),
    # (add awards here when ready)
    ("__blank__", "", ""),
    ("__section__", "~/reach", ""),
    ("GitHub",   "github.com/RanaZaid26194", "accent"),
    ("In",       "linkedin.com/in/rana-zaid26194", "accent"),
    ("Mail",     "ranazaide288@gmail.com", "accent"),
    # ("Web",      "your-portfolio-url", "accent"),
]

# These two palettes are what give the card its GitHub native look. Every
# colour name here (bg, panel, border and so on) is referenced later inside
# the CSS block that render() builds, so if you add a new colour key here
# you also need to add a matching CSS class further down.
THEMES = {
    "dark": {
        "bg": "#0d1117", "panel": "#161b22", "border": "#30363d",
        "text": "#c9d1d9", "muted": "#8b949e", "key": "#3fb950",
        "accent": "#58a6ff", "warn": "#d29922", "art": "#bc8cff",
        "prompt": "#3fb950", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
    "light": {
        "bg": "#ffffff", "panel": "#f6f8fa", "border": "#d0d7de",
        "text": "#1f2328", "muted": "#59636e", "key": "#1a7f37",
        "accent": "#0969da", "warn": "#9a6700", "art": "#8250df",
        "prompt": "#1a7f37", "dot1": "#ff5f56", "dot2": "#ffbd2e", "dot3": "#27c93f",
    },
}

# These constants control the overall geometry of the card, meaning where
# the ascii art sits, where the info panel starts and how tall each line
# of text is. Changing W will resize the whole card, while ART_CW is the
# fixed character width used so the ascii art always lines up correctly no
# matter which monospace font actually gets used to render it.
W = 980
ART_X, ART_Y = 30, 140
ART_CW = 3.9          # forced char width (textLength keeps this exact in any font)
ART_LH = ART_CW * 1.72
INFO_X, INFO_Y, INFO_LH = 448, 92, 17.5
VAL_X = INFO_X + 92


def measure_info_height():
    """Walks the same logic the renderer uses, just to find where content ends."""
    # This function does not draw anything itself. It simply repeats the same
    # step by step spacing rules that render() uses further down, purely so
    # we can figure out the total height of the info column before we know
    # the final height of the whole svg.
    y = INFO_Y
    for label, value, ckey in INFO:
        if label == "__header__":
            y += INFO_LH
        elif label == "__rule__":
            y += 8
        elif label == "__blank__":
            y += 10
        elif label == "__section__":
            y += INFO_LH
        elif label == "__stats__":
            y += INFO_LH
        else:
            y += INFO_LH
    return y


def compute_height(art_lines):
    # The final card height needs to fit whichever column ends up taller,
    # the ascii art on the left or the info text on the right, plus a bit
    # of extra room at the bottom for the closing terminal prompt line.
    art_bottom = ART_Y + len(art_lines) * ART_LH
    info_bottom = measure_info_height()
    return int(max(art_bottom, info_bottom) + 60)  # +60 leaves room for the footer prompt


# This part of the script talks to the real GitHub API to fetch live numbers
# for repos, stars and followers. It is written so that if anything goes
# wrong, whether that is no internet access, a rate limit, or a bad token,
# the whole script still keeps running and simply shows placeholder dashes
# instead of failing the entire GitHub Actions workflow.
# STATS
def fetch_stats():
    stats = {"repos": "-", "stars": "-", "followers": "-"}
    try:
        # A GitHub token is optional here. Passing one just raises the rate
        # limit so the workflow does not get throttled on busy days.
        headers = {"User-Agent": "profile-readme"}
        token = os.environ.get("GITHUB_TOKEN")
        if token:
            headers["Authorization"] = f"Bearer {token}"

        # First we grab the basic user object, which already gives us repo
        # count and follower count in a single request.
        req = urllib.request.Request(
            f"https://api.github.com/users/{USERNAME}", headers=headers)
        user = json.load(urllib.request.urlopen(req, timeout=15))
        stats["repos"] = str(user.get("public_repos", 0))
        stats["followers"] = str(user.get("followers", 0))

        # Stars are not part of that response, so we have to walk through
        # every repo page by page and add up the stargazer count ourselves.
        # We cap this at five pages of a hundred repos each, which is more
        # than enough for almost anyone and keeps the request count sane.
        stars, page = 0, 1
        while page <= 5:
            req = urllib.request.Request(
                f"https://api.github.com/users/{USERNAME}/repos"
                f"?per_page=100&page={page}", headers=headers)
            repos = json.load(urllib.request.urlopen(req, timeout=15))
            if not repos:
                break
            stars += sum(r.get("stargazers_count", 0) for r in repos)
            page += 1
        stats["stars"] = str(stars)
    except Exception as e:  # offline / rate-limited -> keep placeholders
        print(f"[warn] stats fetch failed: {e}")
    return stats


# This is the part that actually builds the svg markup, piece by piece, and
# returns it as one big string. It is written as a list of small text chunks
# that get joined together at the very end, which makes it easy to add or
# remove sections without worrying about string concatenation mistakes.
# RENDER
def render(theme_name, colors, stats, ist_now):
    art_lines = load_portrait()
    H = compute_height(art_lines)

    parts = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" font-family="ui-monospace, SFMono-Regular, '
        f'\'JetBrains Mono\', \'Cascadia Code\', Menlo, Consolas, monospace">'
    )

    # This block defines every CSS class used further down the file, along
    # with the small fade in animation applied to each row and the blinking
    # cursor animation used at the very end of the card.
    parts.append(f"""<style>
    .art  {{ fill:{colors['art']}; font-size:6.2px; white-space:pre; }}
    .key  {{ fill:{colors['key']}; font-size:13px; font-weight:700; }}
    .val  {{ fill:{colors['text']}; font-size:13px; }}
    .acc  {{ fill:{colors['accent']}; font-size:13px; }}
    .wrn  {{ fill:{colors['warn']}; font-size:13px; }}
    .mut  {{ fill:{colors['muted']}; font-size:12px; }}
    .hdr  {{ fill:{colors['accent']}; font-size:15px; font-weight:700; }}
    .sec  {{ fill:{colors['muted']}; font-size:12px; letter-spacing:1px; }}
    .ttl  {{ fill:{colors['muted']}; font-size:12px; }}
    .row  {{ opacity:1; animation: fade .35s ease backwards; }}
    @keyframes fade {{ from {{ opacity:0; transform:translateY(3px); }}
                       to   {{ opacity:1; transform:translateY(0); }} }}
    .cur  {{ fill:{colors['prompt']}; animation: blink 1s steps(1) infinite; }}
    @keyframes blink {{ 50% {{ opacity:0; }} }}
    .artline {{ opacity:1; animation: fade .3s ease backwards; }}
    </style>""")

    # This draws the terminal window itself, meaning the rounded outer
    # frame, the little title bar strip at the top, the divider line under
    # it, the three red, yellow and green window dots, and finally the
    # username title text centred in the middle of that title bar.
    parts.append(
        f'<rect x="1" y="1" width="{W-2}" height="{H-2}" rx="12" '
        f'fill="{colors["bg"]}" stroke="{colors["border"]}" stroke-width="1.5"/>'
    )
    parts.append(
        f'<path d="M1 13 a12 12 0 0 1 12 -12 h{W-26} a12 12 0 0 1 12 12 v25 h{-(W-2)} z" '
        f'fill="{colors["panel"]}"/>'
    )
    parts.append(f'<line x1="1" y1="38" x2="{W-1}" y2="38" stroke="{colors["border"]}"/>')
    for i, c in enumerate(["dot1", "dot2", "dot3"]):
        parts.append(f'<circle cx="{24 + i*20}" cy="20" r="6" fill="{colors[c]}"/>')
    parts.append(
        f'<text x="{W/2}" y="24" class="ttl" text-anchor="middle">'
        f'{escape(USERNAME)} — zsh — 90×26</text>'
    )

    # This is the fake command line shown just under the title bar, styled
    # like someone actually typing "neofetch --profile" into a real shell.
    parts.append(
        f'<text x="{ART_X}" y="66" class="row" style="animation-delay:.05s">'
        f'<tspan class="key">➜</tspan>'
        f'<tspan class="acc" dx="8">~</tspan>'
        f'<tspan class="val" dx="8">neofetch --profile</tspan></text>'
    )

    # Here we draw the ascii art itself, one text line per row. Each line
    # gets its own small animation delay based on its position, so the
    # portrait appears to draw itself in from top to bottom when the card
    # first loads, rather than popping in all at once.
    for i, line in enumerate(art_lines):
        if not line.strip():
            continue
        y = ART_Y + i * ART_LH
        delay = 0.15 + i * 0.012
        tl = len(line) * ART_CW
        parts.append(
            f'<text x="{ART_X}" y="{y:.1f}" class="art artline" xml:space="preserve" '
            f'textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs" '
            f'style="animation-delay:{delay:.2f}s">{escape(line)}</text>'
        )

    # This loop walks through the INFO list defined near the top of the file
    # and draws each row according to its type. Most rows are simple label
    # and value pairs, but a few special labels such as __header__ and
    # __section__ are treated as layout markers instead of visible rows,
    # and get their own drawing rules here.
    y = INFO_Y
    delay = 0.35
    cls_map = {"val": "val", "accent": "acc", "warn": "wrn", "muted": "mut"}

    for label, value, ckey in INFO:
        d = f'style="animation-delay:{delay:.2f}s"'
        if label == "__header__":
            # A big heading line, used once at the very top of the panel.
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="hdr row" {d}>{escape(value)}</text>')
            y += INFO_LH
        elif label == "__rule__":
            # A thin horizontal divider drawn just under the heading.
            parts.append(
                f'<line x1="{INFO_X}" y1="{y-8:.1f}" x2="{W-40}" y2="{y-8:.1f}" '
                f'stroke="{colors["border"]}" class="row" {d}/>'
            )
            y += 8
        elif label == "__blank__":
            # Just adds a little vertical breathing room, nothing is drawn.
            y += 10
            continue
        elif label == "__section__":
            # A small all caps style section label, like ~/stack or ~/projects.
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="sec row" {d}>{escape(value)}</text>')
            y += INFO_LH
        elif label == "__stats__":
            # The live repo, star and follower counts pulled from fetch_stats().
            stat_txt = (f'repos {stats["repos"]}   ·   stars {stats["stars"]}'
                        f'   ·   followers {stats["followers"]}')
            parts.append(
                f'<text x="{INFO_X}" y="{y:.1f}" class="row" {d}>'
                f'<tspan class="key">⚡</tspan>'
                f'<tspan class="val" dx="8">{escape(stat_txt)}</tspan></text>'
            )
            y += INFO_LH
        else:
            # A normal label and value row, such as Role or Focus. If the
            # label is empty, we only draw the value, which is how the
            # wrapped continuation lines under Approach and Learning work.
            cls = cls_map.get(ckey, "val")
            if label:
                parts.append(
                    f'<text x="{INFO_X}" y="{y:.1f}" class="key row" {d}>{escape(label)}</text>'
                )
            parts.append(
                f'<text x="{VAL_X}" y="{y:.1f}" class="{cls} row" {d}>{escape(value)}</text>'
            )
            y += INFO_LH
        delay += 0.07

    # Finally we draw the closing prompt line at the very bottom of the
    # card, complete with a blinking block cursor, plus a small "last
    # updated" timestamp in the bottom right corner so visitors can see
    # exactly when the card was last refreshed by the workflow.
    fy = H - 24
    parts.append(
        f'<text x="{ART_X}" y="{fy}" class="row" style="animation-delay:{delay+0.1:.2f}s">'
        f'<tspan class="key">➜</tspan>'
        f'<tspan class="acc" dx="8">~</tspan>'
        f'<tspan class="val" dx="8">building automation, games and backend systems</tspan>'
        f'<tspan class="cur" dx="8">█</tspan></text>'
    )
    parts.append(
        f'<text x="{W-34}" y="{fy}" class="mut" text-anchor="end">'
        f'last updated {ist_now}</text>'
    )
    parts.append("</svg>")
    return "\n".join(parts)


def main():
    # This is the actual entry point, run directly by the GitHub Actions
    # workflow. It fetches the live stats once, works out the current time
    # in Pakistan Standard Time for the "last updated" stamp, then renders
    # and writes both the dark and light svg files into the assets folder.
    stats = fetch_stats()
    ist = datetime.now(timezone.utc) + timedelta(hours=5, minutes=30)
    stamp = ist.strftime("%d %b %Y, %H:%M IST")
    out = Path(__file__).parent / "assets"
    out.mkdir(exist_ok=True)
    for name, colors in THEMES.items():
        (out / f"{name}.svg").write_text(render(name, colors, stats, stamp), encoding="utf-8")
        print(f"wrote assets/{name}.svg")


if __name__ == "__main__":
    main()